### ISSUE TITLE
Remove invalid cache entries

### ISSUE THREAD

**Issue by froemken** [jweiland-net/avalex#3]
Hello Pascal,

I have 3 Avalex configurations. After executing the scheduler I have 3 Cache entries on PID 0. Now I have removed two of the configurations, but the two old cache entries still exists.
I think it would be better to move the cache entry INTO the configuration record. You can realize it with passthrough or with a real-only field.

Stefan

**Comment by pascal20997** [comment]
Hello Stefan,

thank you for your feedback. I solved your issue for future versions of avalex and avalex_legacy by using the TYPO3 caching framework instead of that scheduler task and custom "caching" records. You can test the new versions by cloning master (for TYPO3 6.2 - 10.2) or legacy (for TYPO3 4.3 - 6.0) :).
